/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";

export const ProductRecord = t.iface([], {
  "Key": "number",
  "Length": "number",
  "Width": "number",
  "Area": "number",
  "DisplayText": "string",
  "DimensionModelNode": "string",
});

const exportedTypeSuite = {
  ProductRecord,
};
export default exportedTypeSuite;
